apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: game-2048-blue
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: 2048-repo
        namespace: flux-system
      interval: 1m
  values:
    image:
      repository: amigoscode/2048
    replicaCount: 1
    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - host: "game-2048-blue.dev.tk.cyma.ie"
          paths:
            - path: /
              pathType: ImplementationSpecific
    resources:
      requests:
        cpu: 20m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 2000Mi
    configMap:
      name: 2048-config-map-blue
      backgroundColor: "#625dfc"
